name: json-feed
version: 1.0.2

category: Web
description: >
  This is an implementation of the JSON Feed spec in Haskell. The spec is
  available at <https://jsonfeed.org>. JSON Feed is similar to the Atom and RSS
  feed formats, but it is serialized as JSON rather than XML.
extra-source-files:
  - CHANGELOG.markdown
  - feeds/*.json
  - package.yaml
  - README.markdown
  - stack.yaml
github: tfausak/json-feed
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: JSON Feed

dependencies:
  aeson: '>= 0.11.2 && < 0.12 || >= 1.0.2 && < 1.5'
  base: '>= 4.9.0 && < 4.12'
  bytestring: '>= 0.10.8 && < 0.11'
  mime-types: '>= 0.1.0 && < 0.2'
  network-uri: '>= 2.6.1 && < 2.7'
  tagsoup: '>= 0.14 && < 0.15'
  text: '>= 1.2.2 && < 1.3'
  time: '>= 1.6.0 && < 1.9'
ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-safe
  - -Wno-unsafe

library:
  source-dirs: library

tests:
  test:
    dependencies:
      filepath: '>= 1.4.1 && < 1.5'
      hspec: '>= 2.2.3 && < 2.6'
      json-feed: -any
    ghc-options:
      - -rtsopts
      - -threaded
    main: Main.hs
    source-dirs: tests
