name: json-feed
version: 0.0.5

category: Web
description: >
  This is an implementation of the JSON Feed spec in Haskell. The spec is
  available at <https://jsonfeed.org>. JSON Feed is similar to the Atom and RSS
  feed formats, but it is serialized as JSON rather than XML.
extra-source-files:
  - feeds/*.json
  - README.markdown
github: tfausak/json-feed
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: JSON Feed

dependencies:
  aeson: ^>= 1.2.3
  base: ^>= 4.10.1
  bytestring: ^>= 0.10.8
  mime-types: ^>= 0.1.0
  network-uri: ^>= 2.6.1
  tagsoup: ^>= 0.14.2
  text: ^>= 1.2.2
  time: ^>= 1.8.0
ghc-options: -Wall

library:
  source-dirs: library

tests:
  test:
    dependencies:
      filepath: ^>= 1.4.1
      hspec: ^>= 2.4.4
      json-feed:
    ghc-options:
      - -rtsopts
      - -threaded
    main: test.hs
    source-dirs: tests
